# Generated by Django 2.2.12 on 2021-01-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('dob', models.DateField(max_length=8)),
                ('department', models.CharField(max_length=5)),
            ],
        ),
    ]
